// WordPress webpack config.
const defaultConfig = require("@wordpress/scripts/config/webpack.config");

// Plugins.
const RemoveEmptyScriptsPlugin = require("webpack-remove-empty-scripts");

// Utilities.
// eslint-disable-next-line no-undef
const path = require("path");

function getThemeBlockStylesEntryPoints() {
  return {
    "styles/core-navigation": path.resolve(
      process.cwd(),
      "src/styles",
      "core-navigation.scss",
    ),
    "styles/core-button": path.resolve(
      process.cwd(),
      "src/styles",
      "core-button.scss",
    ),
    "styles/core-list": path.resolve(
      process.cwd(),
      "src/styles",
      "core-list.scss",
    ),
  };
}

// Add any new entry points by extending the webpack config.
module.exports = {
  ...defaultConfig,
  ...{
    entry: {
      ...getThemeBlockStylesEntryPoints(),
      "scripts/block-variations": path.resolve(
        process.cwd(),
        "src/scripts",
        "block-variations.js",
      ),
    },

    plugins: [
      // Include WP's plugin config.
      ...defaultConfig.plugins,

      // Removes the empty `.js` files generated by webpack but
      // sets it after WP has generated its `*.asset.php` file.
      new RemoveEmptyScriptsPlugin({
        stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
      }),
    ],
  },
};
